# K-Means

In [1]:
import numpy as np
X = np.array([[2.7, 3],[4.2,2.5],[1.5,3],[3.1, 2],[1.6, 1.2],[3.7, 1.8],[1.1,1]])
X

array([[2.7, 3. ],
       [4.2, 2.5],
       [1.5, 3. ],
       [3.1, 2. ],
       [1.6, 1.2],
       [3.7, 1.8],
       [1.1, 1. ]])

In [2]:
mu = np.array([[1.4, 1.7],[2.5, 1.3],[3.0, 1.3]])
mu

array([[1.4, 1.7],
       [2.5, 1.3],
       [3. , 1.3]])

# Iteration 1

In [3]:
d1 = (X-mu[0])**2
d1

array([[1.69, 1.69],
       [7.84, 0.64],
       [0.01, 1.69],
       [2.89, 0.09],
       [0.04, 0.25],
       [5.29, 0.01],
       [0.09, 0.49]])

In [4]:
d2 = (X-mu[1])**2
d2

array([[0.04, 2.89],
       [2.89, 1.44],
       [1.  , 2.89],
       [0.36, 0.49],
       [0.81, 0.01],
       [1.44, 0.25],
       [1.96, 0.09]])

In [5]:
d3 = (X-mu[2])**2
d3

array([[0.09, 2.89],
       [1.44, 1.44],
       [2.25, 2.89],
       [0.01, 0.49],
       [1.96, 0.01],
       [0.49, 0.25],
       [3.61, 0.09]])

In [6]:
for i in range(7):
    ...:     print(d1[i][0]+d1[i][1])

3.380000000000001
8.480000000000002
1.7000000000000002
2.9800000000000004
0.2900000000000001
5.300000000000001
0.5799999999999998


In [7]:
for i in range(7):
    ...:     print(d2[i][0]+d2[i][1])


2.9299999999999997
4.33
3.8899999999999997
0.8500000000000001
0.8199999999999998
1.6900000000000004
2.05


In [8]:
for i in range(7):
    ...:     print(d3[i][0]+d3[i][1])


2.9799999999999995
2.8800000000000003
5.14
0.49999999999999994
1.9699999999999998
0.7400000000000002
3.6999999999999997


In [9]:
s1 = np.array([[1.5,3],[1.6, 1.2],[1.1,1]])
mu[0]= s1.mean(axis=0)

In [10]:
s2 = np.array([[2.7,3]])
mu[1]=s2.mean(axis=0)

In [11]:
s3 = np.array([[4.2, 2.5],[3.1, 2],[3.7, 1.8]])
mu[2]=s3.mean(axis=0)

In [12]:
mu

array([[1.4       , 1.73333333],
       [2.7       , 3.        ],
       [3.66666667, 2.1       ]])

# Iteration 2

In [13]:
d1 = (X-mu[0])**2
d1

array([[1.69000000e+00, 1.60444444e+00],
       [7.84000000e+00, 5.87777778e-01],
       [1.00000000e-02, 1.60444444e+00],
       [2.89000000e+00, 7.11111111e-02],
       [4.00000000e-02, 2.84444444e-01],
       [5.29000000e+00, 4.44444444e-03],
       [9.00000000e-02, 5.37777778e-01]])

In [15]:
d2 = (X-mu[1])**2
d2

array([[0.  , 0.  ],
       [2.25, 0.25],
       [1.44, 0.  ],
       [0.16, 1.  ],
       [1.21, 3.24],
       [1.  , 1.44],
       [2.56, 4.  ]])

In [16]:
d3 = (X-mu[2])**2
d3

array([[9.34444444e-01, 8.10000000e-01],
       [2.84444444e-01, 1.60000000e-01],
       [4.69444444e+00, 8.10000000e-01],
       [3.21111111e-01, 1.00000000e-02],
       [4.27111111e+00, 8.10000000e-01],
       [1.11111111e-03, 9.00000000e-02],
       [6.58777778e+00, 1.21000000e+00]])

In [18]:
for i in range(7):
     print(d1[i][0]+d1[i][1])


3.2944444444444443
8.427777777777777
1.6144444444444443
2.961111111111111
0.32444444444444454
5.294444444444443
0.627777777777778


In [19]:
for i in range(7):
    print(d2[i][0]+d2[i][1])


0.0
2.5
1.4400000000000004
1.16
4.45
2.44
6.5600000000000005


In [20]:
for i in range(7):
    print(d3[i][0]+d3[i][1])

1.7444444444444436
0.4444444444444447
5.504444444444443
0.33111111111111086
5.0811111111111105
0.09111111111111116
7.797777777777776


In [21]:
s1 = np.array([[1.6, 1.2],[1.1, 1]])
mu[0]=s1.mean(axis=0)

In [22]:
s2 = np.array([[2.7,3],[1.5, 3]])
mu[1]=s2.mean(axis=0)

In [23]:
s3 = np.array([[4.2,2.5],[3.1,2],[3.7,1.8]])
mu[2]=s3.mean(axis=0)

In [24]:
mu

array([[1.35      , 1.1       ],
       [2.1       , 3.        ],
       [3.66666667, 2.1       ]])